<?php if($this->getQuote()->getData() == array()): ?>

<div class="page-title">
    <h1><?php echo $this->__('Request for Quote') ?></h1>
</div>
<div class="cart-empty">
  <p><?php echo $this->__('No Items to display.'); ?></p>
  <p><?php echo $this->__('Click <a href="%s">here</a> to continue shopping.', $this->getUrl()) ?></p>
</div>

<?php else: ?>

<?php $productNames = $this->getNotSalableProductNames($this->getQuote()); ?>

<div class="page-title">
    <h3><?php echo $this->__('Request for Quote') ?></h3>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<form method='post' id="quotelist" name="quotelist" action='<?php echo $this->getUrl('qquoteadv/index/quoteRequest', array('_secure' => true)) ?>' >
<table cellspacing="0" border="0" id="shopping-cart-table" class="data-table cart-table">
    <col width="30" />
    <col width="75" />
	<col />
    <col width="10" />    
    <col width="250"/>
    <col width="60" />
    <col width="60" />
    <thead>
       <tr>
        <th class="a-center"><?php echo $this->__('Remove') ?></th>
        <th class="a-center">&nbsp;</th>
        <th><?php echo $this->__('Product Name') ?></th>
        <th>&nbsp;</th>
        <th><?php echo $this->__('Request information') ?></th>
        <th class="a-center"><?php echo $this->__('Unit price') ?></th>
        <th class="a-center"><?php echo $this->__('Qty') ?> <span class="required">*</span></th>
       </tr>
    </thead>
    <tbody>
		<?php
        $i = 0;
		foreach($this->getQuote() as $item):

			$product = $this->getProduct($item->getProductId());
			?>
			<tr>
				<td class="a-center">

				<input type="hidden" id="quote_id" name="quote_id" value="<?php echo $item->getQuoteId() ?>">
				<input type="hidden" class="input-text" name="quote[<?php echo $item->getId() ?>][product]" value="<?php echo $item->getProductId(); ?>" size="3" />
				<input type="hidden" class="input-text" name="quote_request[<?php echo $item->getId() ?>][product_id]" value="<?php echo $item->getProductId(); ?>" size="6" />
					<a title="<?php echo $this->__('Remove item')?>" href="<?php echo $this->getUrl('qquoteadv/index/delete',array('id'=>$item->getId())); ?>"><img src="<?php echo $this->getSkinUrl('images/btn_trash.gif') ?>" width="16" height="16" alt="<?php echo $this->__('Remove item')?>" /></a>

				</td>
				<td><a class="product-image" href="<?php echo $product->getProductUrl(); ?>"><img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail', $item->getSmallImage())->resize(75); ?>" alt="<?php echo $item->getName(); ?>" /></a>

				</td>
				<td class="attributes-col"><h4 class="title">
<?php if (1): //$product->hasProductUrl()):?>
    <a href="<?php echo $product->getProductUrl() ?>"><?php echo $this->htmlEscape($product->getName()) ?></a>
<?php else: ?>
    <?php echo $this->htmlEscape($product->getName()) ?>
<?php endif; ?>
</h4>
                                              
<?php
if($product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE || $product->isConfigurable()  || $product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_SIMPLE):
    $quoteByProduct = Mage::helper('qquoteadv')->getQuoteItem($product, $item->getAttribute());
	
    foreach($quoteByProduct->getAllItems() as $_item) {
        if( $_item->getProductId() == $product->getId() ) {
			echo $this->getItemHtml($_item);             
        }
    }
	$qty = $quoteByProduct->getItemsQty();	
	$_finalPrice = $quoteByProduct->getSubtotal() / ($qty>0?$qty:1);
/*else:  
  	$quoteByProduct = Mage::helper('qquoteadv')->getQuoteItem($product, $item->getAttribute());
	$qty = $quoteByProduct->getItemsQty();	
	$_finalPrice = $quoteByProduct->getSubtotal() / ($qty>0?$qty:1);
?>
    <?php if($product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_SIMPLE) : ?>
    <?php    $_options =  $this->getOptionList($product, $item->getAttribute()); ?>
    
    <dl class="item-options">
        <?php if(is_array($_options)): ?>
            <?php foreach ($_options as $label=>$_option) : ?>
            <?php if(empty($label)) continue; ?>
            <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
            <dt><?php echo $this->htmlEscape($label) ?></dt>
            <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                <div class="truncated_full_value">
                    <dl class="item-options">
                        <dt><?php echo $this->htmlEscape($label) ?></dt>
                        <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                    </dl>
                </div>
                <?php endif; ?>
            </dd>
            <?php endforeach; ?>
        <?php endif; ?>
     </dl>
    <?php endif; ?>
    
<?php */ endif; ?>
</td>
                <td><a href="<?php echo $this->getUrl('qquoteadv/index/configure' , array('id'=>$item->getId()) )?>"><?php echo $this->__("Edit")?></a> <br/>
                    </td>
				<td>
                        <?php if($i>0):?>
                        <textarea name="quote_request[<?php echo $item->getId() ?>][client_request]"
                                     rows="4"  style="width:98%;" >&nbsp;</textarea>
                        <?php else: ?>
                        <div id="parent">
                            <textarea id="textArea" name="quote_request[<?php echo $item->getId() ?>][client_request]"
                                         rows="4"  style="width:98%; position: absolute;" ></textarea>
                            <div onclick="$('comment').hide(); $('textArea').focus();"  id="comment">
                                    <?php echo $this->__('Be advised to enter your comments')?>
                            </div>
                        </div>    
                        <?php endif; ?>                    
				</td>				                				
				<td>
				    <?php if (Mage::helper('qquoteadv/not2order')->getShowPrice($product)): ?>
				    <?php echo Mage::helper('checkout')->formatPrice($_finalPrice)?>
				    <?php endif; ?>
				</td>
				<td nowrap="nowrap">
<div id="qdiv_<?php echo $item->getId() ?>" nowrap="nowrap">
	<input type="text"  class="required-entry validate-zero-or-greater required-entry input-text loading" size="6"
			name="quote_request[<?php echo $item->getId() ?>][qty][]" value="<?php echo $item->getQty(); ?>"  />
</div>
<div>
   <a class="pad" href="#" onClick="addNewLine(<?php echo $item->getId() ?>, 'quote_request[<?php echo $item->getId() ?>][qty][]'); return false;"><?php echo $this->__('Add Qty') ?></a>
</div>
				<input type="hidden" name="quote[<?php echo $item->getId() ?>][qty]" value="<?php echo $item->getQty(); ?>" size="3" />&nbsp;
				<input type="hidden" name="quote[<?php echo $item->getId() ?>][attributeEncode]" value="<?php echo base64_encode($item->getAttribute()) ?>" />
				<input type="hidden" name="quote[<?php echo $item->getId() ?>][product]" value="<?php echo $product->getId() ?>" />
				<input type="hidden" name="quote[<?php echo $item->getId() ?>][quoteid]" value="<?php echo $item->getId() ?>" />
				</td>
			</tr>
			<?php
			$i++;
		endforeach;
		?>
		</tbody>
		<tfoot>
		<tr>
			<td colspan="100" class="a-right">
                <?php if($this->getContinueShoppingUrl()): ?>
                    <button class="button btn-continue" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')" type="button"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
                <?php endif; ?>

                <?php $action = "setLocation('".$this->getUrl('qquoteadv/index/switch2Order')."');";

                if(count($productNames)>0){
                    $action = 'initMsg();';
                }
                ?>

                <button type="button" onclick="<?php echo $action; ?>" title="<?php echo $this->__('Move to Shopping cart') ?>"
                class="button btn-update" ><span><span><?php echo $this->__('Move to Shopping cart') ?></span></span></button>
			</td>
		</tr>
		</tfoot>

	</table>
	<script type="text/javascript">decorateTable('shopping-cart-table')</script>

<?php echo $this->getChildHtml('qquote.address'); ?>

	<div style="float:right;">
		<input type='hidden' name='customer[is_quote]' value='1' />
		<input style="display:none;" type='submit' name='submitOrder' id="submitOrder" class='form-button'  
			   value="<?php echo $this->__('Request quote') ?>" />

        <button onclick="$('submitOrder').click(); event.preventDefault();  event.stopPropagation();" class="button btn-proceed-checkout btn-checkout" 
                title="<?php echo $this->__('Request quote') ?>" type="button"><span><span><?php echo $this->__('Request quote') ?></span></span></button>        
	</div>

</div>
</form>
<script type="text/javascript">
//<![CDATA[
	var quotelistForm = new VarienForm('quotelist');
	new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
	$('country').addClassName('w224');
//]]>
</script>


<?php 
//#show pop-up window
if(count($productNames)>0){
    echo $this->getLayout()->createBlock("core/template")->setTemplate('qquoteadv/quote_lightbox.phtml')->setProductNames($productNames)->toHtml(); 
}
?>


<script language="javascript">

var pool = new Array();

function addNewLine(itemId, inputName){
    if (!pool[itemId]){
	   pool[itemId] = 1;
   }

   index = pool[itemId];
   index++;
   pool[itemId] = index;

   var parentElemt = document.getElementById('qdiv_'+itemId);
   var childElem = document.createElement('div');
   childElem.setAttribute("id",'div_' + itemId + '_' + index);
   parentDiv='div_' + itemId + '_' + index;
   inputField='quote_' + itemId + '_' + index;
   link = '&nbsp;&nbsp;<a style="text-decoration:none;" href="#"  onClick="removeElement(\''+parentDiv+'\', \''+inputField+'\'); $(\''+parentDiv+'\').hide()"><img style="vertical-align: bottom;bottom;width:19px;height:18px;" src="<?php echo $this->getSkinUrl('images/minus-icon.png')?>"></a>';

   childElem.innerHTML = '<input size="6" type="text" name="'+inputName+'"  id="quote_' + itemId + '_' + index +'" value=""  class="required-entry validate-zero-or-greater required-entry input-text m5">'+link;

   parentElemt.appendChild(childElem);
}

function removeElement(parentElemt, childElemt) {
  var parentDiv = document.getElementById(parentElemt);
  var childElemt = document.getElementById(childElemt);
  parentDiv.removeChild(childElemt);
}
</script>
<?php endif; ?>
