<?php   $_product = $this->getProduct();
        $addCartUrl = $this->getAddToCartUrl($_product);
		$html		= '';
		$ordermode	= '';
		$quotemode	= '';
		$btnQuoteTitle = $this->__("Add to Quote");
		$btnCartTitle  = $this->__('Add to Cart');
                
                $allowed_to_quotemode = Mage::getModel("catalog/product")->load($_product->getId())->getAllowedToQuotemode();

		if( $_product->isSaleable() ) {
			$cartBtn = 	'<button type="button" title="%s" class="button btn-cart" onclick="setLocation(\'%s\')"><span><span>%s</span></span></button><br />';
			$ordermode = sprintf($cartBtn, $btnCartTitle, $addCartUrl, $btnCartTitle);
		}else{
			if (!$_product->isAvailable()) :
			$ordermode ='<p class="availability out-of-stock"><span>'.$this->__('Available in 2-3 days').'</span></p>';
			endif;
		}

		if( $allowed_to_quotemode==1 ) {
                    
                        $isAjax = Mage::getStoreConfig('qquoteadv/layout/ajax_add'); 
                        if($isAjax) {
                              $actionQuote = "addQuoteList('%s', $isAjax );"; 
                        } else {
                             $actionQuote = "setLocation('%s');";
                        }  
                     
			$quoteBtn = '<button title="%s" type="button" class="button btn-cart" style="margin-top:1px" onclick="'.$actionQuote.'"><span ><span>%s</span></span></button>';
			if( $_product->getTypeId() == 'grouped' ){ 
				$url = $_product->getProductUrl()."?c2qredirect=1";
			}else{
				$url = $this->helper('qquoteadv/catalog_product_data')->getUrlAdd2QquoteadvList($_product);
			}

			$quotemode = sprintf($quoteBtn, $btnQuoteTitle, $url, $btnQuoteTitle );
		}

		$html.="<p>$ordermode $quotemode</p>";
echo $html;
