<?php $_quote = $this->getQuote() ?>
<table cellspacing="0" cellpadding="0" border="0" width="650" style="border:1px solid #EAEAEA;">
    <thead>
        <tr>
            <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Item') ?></th>
            <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Sku') ?></th>
            <th align="center" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Tier/Qty') ?></th>
            <th align="center" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Price') ?></th>
            <th align="right" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Subtotal') ?></th>
        </tr>
    </thead>
    <?php $i=0; foreach ($this->getAllItems() as $_item): ?>
    <?php if($_item->getParentItem()) continue; else $i++; ?>
    <tbody<?php echo $i%2 ? ' bgcolor="#F6F6F6"' : '' ?>>
        <?php echo $this->getLayout()->getBlock('qquoteadv_item')->setItem($_item)->toHtml(); ?>
    </tbody>
    <?php endforeach; ?>
    <tbody>
        <tr class="subtotal">
            <td colspan="4" align="right" style="padding:3px 9px"><?php echo $this->__('Subtotal'); ?></td>
            <td align="right" style="padding:3px 9px"><span class="price"><a href="<?php echo $this->getUrl('qquoteadv/view/history/'); ?>">Login</a></span></td>
        </tr>
        <tr class="shipping">
            <td colspan="4" align="right" style="padding:3px 9px"><?php echo $this->__('Shipping & Handling'); ?></td>
            <td align="right" style="padding:3px 9px"><span class="price"><a href="<?php echo $this->getUrl('qquoteadv/view/history/'); ?>">Login</a></span></td>
        </tr>
        <tr class="grand_total">
            <td colspan="4" align="right" style="padding:3px 9px"><strong><?php echo $this->__('Grand Total'); ?></strong></td>
            <td align="right" style="padding:3px 9px"><strong><span class="price"><a href="<?php echo $this->getUrl('qquoteadv/view/history/'); ?>">Login</a></span></strong></td>
        </tr>
    </tbody>
</table>